spring.application.name=carbon-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/carbon_tracker
spring.datasource.username=postgres
spring.datasource.password=carbonfootprint
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Google Gemini API Configuration
gemini.api.key=${Geminiapikey}
# Notice we append the key to the URL later in the code, so just store the base URL here
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
